### ISSUE TITLE
Apply instantaneous velocity on D&D release

### ISSUE THREAD

**Issue by jonesjonathan** [Group-47-Capstone-2019/Immersive-Web-VR-AR#107]
- [x] Get position from previous frame
- [x] Get delta time between frames
- [x] Get vector from old position to new position
- [x] Get magnitude of difference vector and apply delta to calculate instantaneous velocity

**Comment by brassev** [comment]
In the pendulum-scene branch I have a sample implementation for throwing the ball in falling.js
