### ISSUE TITLE
Check chrome version compatibility

### ISSUE THREAD

**Issue by jonesjonathan** [Group-47-Capstone-2019/Immersive-Web-VR-AR#62]
Check for chrome version before running any navigator.xr commands. Prevents older versions of chrome from breaking.

**Comment by darktears** [comment]
I don't think we should care about that. Ultimately things will get stable and less bumpy. Rather than code to detect the version, just add a label somewhere in the UI with a "require Chrome 7x or later".

**Comment by jonesjonathan** [comment]
So the API itself will handle that later on then?
